<a href="https://colab.research.google.com/github/justamy20/scikit-learn-Cookbook/blob/main/Chapter_02.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Bab 2: Alur Kerja Pra-Model dan Pemrosesan Data

<div class="alert alert-info">
<b>Ringkasan Bab:</b> Bab ini berfokus pada teknik pembersihan data (data cleaning) dan transformasi fitur. Kita akan mempelajari cara menangani data yang hilang, mengubah data teks (kategori) menjadi angka, serta melakukan penskalaan fitur (feature scaling).
</div>

## 1. Menangani Data yang Hilang (Imputasi)
Data di dunia nyata seringkali tidak lengkap. scikit-learn menyediakan `SimpleImputer` untuk mengisi nilai yang kosong (NaN) menggunakan strategi tertentu seperti rata-rata (mean), median, atau nilai yang paling sering muncul (most frequent).

In [1]:
import numpy as np
from sklearn.impute import SimpleImputer

# Data contoh dengan nilai yang hilang (np.nan)
X_missing = [[1, 2], [np.nan, 3], [7, 6]]

# Strategi: Mengisi nilai yang hilang dengan rata-rata (mean)
imputer = SimpleImputer(strategy='mean')
X_filled = imputer.fit_transform(X_missing)

print("Data Asli dengan NaN:\n", X_missing)
print("\nData Setelah Imputasi (Mean):\n", X_filled)

Data Asli dengan NaN:
 [[1, 2], [nan, 3], [7, 6]]

Data Setelah Imputasi (Mean):
 [[1. 2.]
 [4. 3.]
 [7. 6.]]


---
## 2. Mengolah Data Kategorikal (Encoding)
Komputer tidak mengerti kata-kata seperti "Merah" atau "Biru", mereka hanya mengerti angka.
* **OrdinalEncoder**: Untuk data kategori yang punya tingkatan (misal: Rendah, Sedang, Tinggi).
* **OneHotEncoder**: Untuk data kategori yang tidak punya tingkatan (misal: Nama Kota, Jenis Kelamin).

In [2]:
from sklearn.preprocessing import OneHotEncoder
import numpy as np

# Data contoh kategori
X_cat = np.array([['Jakarta'], ['Bandung'], ['Surabaya'], ['Jakarta']])

# Inisialisasi OneHotEncoder
encoder = OneHotEncoder(sparse_output=False)
X_encoded = encoder.fit_transform(X_cat)

print("Kategori Asli:\n", X_cat.flatten())
print("\nHasil One-Hot Encoding:\n", X_encoded)
print("\nNama Fitur Baru:", encoder.get_feature_names_out())

Kategori Asli:
 ['Jakarta' 'Bandung' 'Surabaya' 'Jakarta']

Hasil One-Hot Encoding:
 [[0. 1. 0.]
 [1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]]

Nama Fitur Baru: ['x0_Bandung' 'x0_Jakarta' 'x0_Surabaya']


---
## 3. Penskalaan Fitur (Feature Scaling)
Banyak algoritma Machine Learning (seperti KNN atau SVM) sangat sensitif terhadap skala angka. Jika satu fitur bernilai ribuan dan fitur lain bernilai satuan, model bisa menjadi bias.
* **MinMaxScaler**: Mengubah data ke rentang 0 sampai 1.
* **StandardScaler**: Mengubah data agar memiliki rata-rata 0 dan standar deviasi 1.

In [3]:
from sklearn.preprocessing import MinMaxScaler, StandardScaler

X_data = np.array([[10, 0.001], [20, 0.005], [30, 0.010]])

# MinMaxScaler (0 ke 1)
min_max = MinMaxScaler()
X_minmax = min_max.fit_transform(X_data)

# StandardScaler
std_scaler = StandardScaler()
X_std = std_scaler.fit_transform(X_data)

print("Data Asli:\n", X_data)
print("\nHasil MinMaxScaler (0-1):\n", X_minmax)
print("\nHasil StandardScaler (Mean 0, Std 1):\n", X_std)

Data Asli:
 [[1.e+01 1.e-03]
 [2.e+01 5.e-03]
 [3.e+01 1.e-02]]

Hasil MinMaxScaler (0-1):
 [[0.         0.        ]
 [0.5        0.44444444]
 [1.         1.        ]]

Hasil StandardScaler (Mean 0, Std 1):
 [[-1.22474487 -1.1769647 ]
 [ 0.         -0.09053575]
 [ 1.22474487  1.26750044]]


---
## 4. Mendeteksi dan Menangani Outlier
Outlier adalah data yang nilainya sangat jauh berbeda dari data lainnya. Salah satu cara sederhana adalah menggunakan **Binarizer** untuk mengubah nilai kontinu menjadi nilai biner (0 atau 1) berdasarkan ambang batas (*threshold*) tertentu.